package com.appium.ApiDemos_debug.suites.home.nested.graphics.strings;

public class GraphicsStrings {
    public static final String ALPHA_BITMAP = "AlphaBitmap";
    public static final String ANIMATE_DRAWABLES = "AnimateDrawables";
    public static final String ARCS = "Arcs";
    public static final String BITMAP_DECODE = "BitmapDecode";
    public static final String BITMAP_MESH = "BitmapMesh";
    public static final String BITMAP_PIXELS = "BitmapPixels";
    public static final String CAMERA_PREVIEW = "CameraPreview";
    public static final String CLIPPING = "Clipping";
    public static final String COLOR_FILTERS = "ColorFilters";
    public static final String COLOR_MATRIX = "ColorMatrix";
    public static final String COMPASS = "Compass";
    public static final String CREATE_BITMAP = "CreateBitmap";
    public static final String DENSITY = "Density";
    public static final String DRAWABLE = "Drawable";
    public static final String FINGER_PAINT = "FingerPaint";
    public static final String LAYERS = "Layers";
    public static final String MEASURE_TEXT = "MeasureText";
    public static final String OPEN_GL_ES = "OpenGL ES";
    public static final String PATH_EFFECTS = "PathEffects";
    public static final String PATH_FILL_TYPES = "PathFillTypes";
    public static final String PATTERNS = "Patterns";
    public static final String POINTS = "Points";
    public static final String POLY_TO_POLY = "PolyToPoly";
    public static final String PURGEABLE_BITMAP = "PurgeableBitmap";
    public static final String REGIONS = "Regions";
    public static final String ROUND_RECTS = "RoundRects";
    public static final String SCALE_TO_FIT = "ScaleToFit";
    public static final String SENSOR_TEST = "SensorTest";
    public static final String SURFACE_WINDOW = "Surface Window";
    public static final String SURFACE_VIEW_OVERLAY = "SurfaceView Overlay";
    public static final String SWEEP = "Sweep";
    public static final String TEXT_ALIGN = "Text Align";
    public static final String TOUCH_PAINT = "Touch Paint";
    public static final String TYPEFACES = "Typefaces";
    public static final String UNICODE_CHART = "UnicodeChart";
    public static final String VERTICES = "Vertices";
    public static final String XFERMODES = "Xfermodes";
}
