package com.appium.ApiDemos_debug.suites.home.nested.views.strings;

public class ViewsStrings {
    public static final String ANIMATION = "Animation";
    public static final String AUTO_COMPLETE = "Auto Complete";
    public static final String BUTTONS = "Buttons";
    public static final String CHRONOMETER = "Chronometer";
    public static final String CONTROLS = "Controls";
    public static final String CUSTOM = "Custom";
    public static final String DATE_WIDGETS = "Date Widgets";
    public static final String DRAG_AND_DROP = "Drag and Drop";
    public static final String EXPANDABLE_LISTS = "Expandable Lists";
    public static final String FOCUS = "Focus";
    public static final String GALLERY = "Gallery";
    public static final String GAME_CONTROLLER_INPUT = "Game Controller Input";
    public static final String GRID = "Grid";
    public static final String HOVER_EVENTS = "Hover Events";
    public static final String IMAGE_BUTTON = "ImageButton";
    public static final String IMAGE_SWITCHER = "ImageSwitcher";
    public static final String IMAGE_VIEW = "ImageView";
    public static final String LAYOUT_ANIMATION = "Layout Animation";
    public static final String LAYOUTS = "Layouts";
    public static final String LISTS = "Lists";
    public static final String PICKER = "Picker";
    public static final String POPUP_MENU = "Popup Menu";
    public static final String PROGRESS_BAR = "Progress Bar";
    public static final String RADIO_GROUP = "Radio Group";
    public static final String RATING_BAR = "Rating Bar";
    public static final String ROTATING_BUTTON = "Rotating Button";
    public static final String SCROLL_BARS = "ScrollBars";
    public static final String SEARCH_VIEW = "Search View";
    public static final String SECURE_VIEW = "Secure View";
    public static final String SEEK_BAR = "Seek Bar";
    public static final String SPINNER = "Spinner";
    public static final String SPLITTING_TOUCHES_ACROSS_VIEWS = "Splitting Touches across Views";
    public static final String SWITCHES = "Switches";
    public static final String SYSTEM_UI_VISIBILITY = "System UI Visibility";
    public static final String TABS = "Tabs";
    public static final String TEXT_CLOCK = "TextClock";
    public static final String TEXT_FIELDS = "TextFields";
    public static final String TEXT_SWITCHER = "TextSwitcher";
    public static final String VISIBILITY = "Visibility";
    public static final String WEB_VIEW = "WebView";
    public static final String WEB_VIEW_TWO = "WebView2";
    public static final String WEB_VIEW_THREE = "WebView3";
}
